version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Starting pre-build phase..."

  build:
    commands:
      - echo "Building the project"
      - echo "Building completed on date"

  post_build:
    commands:
      - echo "Starting post-build phase..."

artifacts:
  files:
    - '**/*'
  discard-paths: no
